FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY tsconfig.json ./
COPY nest-cli.json ./
COPY src ./src

RUN npx nest build

EXPOSE 3002
EXPOSE 3003

CMD ["node", "dist/main"]